
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#pragma once

            #include <glib-object.h>


            G_BEGIN_DECLS

/* enumerations from "as-agreement.h" */


GType as_agreement_kind_get_type (void);
#define AS_TYPE_AGREEMENT_KIND (as_agreement_kind_get_type())

/* enumerations from "as-artifact.h" */


GType as_size_kind_get_type (void);
#define AS_TYPE_SIZE_KIND (as_size_kind_get_type())


GType as_artifact_kind_get_type (void);
#define AS_TYPE_ARTIFACT_KIND (as_artifact_kind_get_type())

/* enumerations from "as-branding.h" */


GType as_color_kind_get_type (void);
#define AS_TYPE_COLOR_KIND (as_color_kind_get_type())


GType as_color_scheme_kind_get_type (void);
#define AS_TYPE_COLOR_SCHEME_KIND (as_color_scheme_kind_get_type())

/* enumerations from "as-bundle.h" */


GType as_bundle_kind_get_type (void);
#define AS_TYPE_BUNDLE_KIND (as_bundle_kind_get_type())

/* enumerations from "as-checksum.h" */


GType as_checksum_kind_get_type (void);
#define AS_TYPE_CHECKSUM_KIND (as_checksum_kind_get_type())

/* enumerations from "as-component-box.h" */


GType as_component_box_flags_get_type (void);
#define AS_TYPE_COMPONENT_BOX_FLAGS (as_component_box_flags_get_type())

/* enumerations from "as-component.h" */


GType as_component_kind_get_type (void);
#define AS_TYPE_COMPONENT_KIND (as_component_kind_get_type())


GType as_merge_kind_get_type (void);
#define AS_TYPE_MERGE_KIND (as_merge_kind_get_type())


GType as_component_scope_get_type (void);
#define AS_TYPE_COMPONENT_SCOPE (as_component_scope_get_type())


GType as_url_kind_get_type (void);
#define AS_TYPE_URL_KIND (as_url_kind_get_type())


GType as_value_flags_get_type (void);
#define AS_TYPE_VALUE_FLAGS (as_value_flags_get_type())


GType as_releases_kind_get_type (void);
#define AS_TYPE_RELEASES_KIND (as_releases_kind_get_type())

/* enumerations from "as-content-rating.h" */


GType as_content_rating_system_get_type (void);
#define AS_TYPE_CONTENT_RATING_SYSTEM (as_content_rating_system_get_type())


GType as_content_rating_value_get_type (void);
#define AS_TYPE_CONTENT_RATING_VALUE (as_content_rating_value_get_type())

/* enumerations from "as-context.h" */


GType as_format_version_get_type (void);
#define AS_TYPE_FORMAT_VERSION (as_format_version_get_type())


GType as_format_style_get_type (void);
#define AS_TYPE_FORMAT_STYLE (as_format_style_get_type())


GType as_format_kind_get_type (void);
#define AS_TYPE_FORMAT_KIND (as_format_kind_get_type())

/* enumerations from "as-icon.h" */


GType as_icon_kind_get_type (void);
#define AS_TYPE_ICON_KIND (as_icon_kind_get_type())

/* enumerations from "as-image.h" */


GType as_image_kind_get_type (void);
#define AS_TYPE_IMAGE_KIND (as_image_kind_get_type())

/* enumerations from "as-issue.h" */


GType as_issue_kind_get_type (void);
#define AS_TYPE_ISSUE_KIND (as_issue_kind_get_type())

/* enumerations from "as-launchable.h" */


GType as_launchable_kind_get_type (void);
#define AS_TYPE_LAUNCHABLE_KIND (as_launchable_kind_get_type())

/* enumerations from "as-metadata.h" */


GType as_parse_flags_get_type (void);
#define AS_TYPE_PARSE_FLAGS (as_parse_flags_get_type())


GType as_metadata_error_get_type (void);
#define AS_TYPE_METADATA_ERROR (as_metadata_error_get_type())

/* enumerations from "as-pool.h" */


GType as_pool_flags_get_type (void);
#define AS_TYPE_POOL_FLAGS (as_pool_flags_get_type())


GType as_cache_flags_get_type (void);
#define AS_TYPE_CACHE_FLAGS (as_cache_flags_get_type())


GType as_pool_error_get_type (void);
#define AS_TYPE_POOL_ERROR (as_pool_error_get_type())

/* enumerations from "as-provided.h" */


GType as_provided_kind_get_type (void);
#define AS_TYPE_PROVIDED_KIND (as_provided_kind_get_type())

/* enumerations from "as-relation.h" */


GType as_check_result_get_type (void);
#define AS_TYPE_CHECK_RESULT (as_check_result_get_type())


GType as_relation_kind_get_type (void);
#define AS_TYPE_RELATION_KIND (as_relation_kind_get_type())


GType as_relation_item_kind_get_type (void);
#define AS_TYPE_RELATION_ITEM_KIND (as_relation_item_kind_get_type())


GType as_relation_compare_get_type (void);
#define AS_TYPE_RELATION_COMPARE (as_relation_compare_get_type())


GType as_control_kind_get_type (void);
#define AS_TYPE_CONTROL_KIND (as_control_kind_get_type())


GType as_display_side_kind_get_type (void);
#define AS_TYPE_DISPLAY_SIDE_KIND (as_display_side_kind_get_type())


GType as_internet_kind_get_type (void);
#define AS_TYPE_INTERNET_KIND (as_internet_kind_get_type())


GType as_relation_error_get_type (void);
#define AS_TYPE_RELATION_ERROR (as_relation_error_get_type())

/* enumerations from "as-release.h" */


GType as_release_kind_get_type (void);
#define AS_TYPE_RELEASE_KIND (as_release_kind_get_type())


GType as_urgency_kind_get_type (void);
#define AS_TYPE_URGENCY_KIND (as_urgency_kind_get_type())


GType as_release_url_kind_get_type (void);
#define AS_TYPE_RELEASE_URL_KIND (as_release_url_kind_get_type())

/* enumerations from "as-review.h" */


GType as_review_flags_get_type (void);
#define AS_TYPE_REVIEW_FLAGS (as_review_flags_get_type())

/* enumerations from "as-screenshot.h" */


GType as_screenshot_kind_get_type (void);
#define AS_TYPE_SCREENSHOT_KIND (as_screenshot_kind_get_type())


GType as_screenshot_media_kind_get_type (void);
#define AS_TYPE_SCREENSHOT_MEDIA_KIND (as_screenshot_media_kind_get_type())

/* enumerations from "as-suggested.h" */


GType as_suggested_kind_get_type (void);
#define AS_TYPE_SUGGESTED_KIND (as_suggested_kind_get_type())

/* enumerations from "as-system-info.h" */


GType as_system_info_error_get_type (void);
#define AS_TYPE_SYSTEM_INFO_ERROR (as_system_info_error_get_type())

/* enumerations from "as-translation.h" */


GType as_translation_kind_get_type (void);
#define AS_TYPE_TRANSLATION_KIND (as_translation_kind_get_type())

/* enumerations from "as-utils.h" */


GType as_utils_error_get_type (void);
#define AS_TYPE_UTILS_ERROR (as_utils_error_get_type())


GType as_data_id_match_flags_get_type (void);
#define AS_TYPE_DATA_ID_MATCH_FLAGS (as_data_id_match_flags_get_type())


GType as_metadata_location_get_type (void);
#define AS_TYPE_METADATA_LOCATION (as_metadata_location_get_type())

/* enumerations from "as-validator-issue.h" */


GType as_issue_severity_get_type (void);
#define AS_TYPE_ISSUE_SEVERITY (as_issue_severity_get_type())

/* enumerations from "as-validator.h" */


GType as_validator_error_get_type (void);
#define AS_TYPE_VALIDATOR_ERROR (as_validator_error_get_type())

/* enumerations from "as-vercmp.h" */


GType as_vercmp_flags_get_type (void);
#define AS_TYPE_VERCMP_FLAGS (as_vercmp_flags_get_type())

/* enumerations from "as-video.h" */


GType as_video_codec_kind_get_type (void);
#define AS_TYPE_VIDEO_CODEC_KIND (as_video_codec_kind_get_type())


GType as_video_container_kind_get_type (void);
#define AS_TYPE_VIDEO_CONTAINER_KIND (as_video_container_kind_get_type())

G_END_DECLS

/* Generated data ends here */

