#
# Docker file for AppStream CI tests on Fedora targeting latest stable
#
FROM registry.fedoraproject.org/fedora:latest

# prepare
RUN mkdir -p /build/ci/

# install build dependencies
COPY install-deps-rpm.sh /build/ci/
RUN chmod +x /build/ci/install-deps-rpm.sh && /build/ci/install-deps-rpm.sh

# finish
WORKDIR /build
