#
# Docker file for AppStream CI tests on Debian Stable
#
FROM debian:bullseye

# prepare
RUN mkdir -p /build/ci/

# install build dependencies
COPY install-deps-deb.sh /build/ci/
RUN chmod +x /build/ci/install-deps-deb.sh && /build/ci/install-deps-deb.sh

# finish
WORKDIR /build
