
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#pragma once

            #include <glib-object.h>


            G_BEGIN_DECLS

/* enumerations from "asc-canvas.h" */


GType asc_canvas_error_get_type (void);
#define ASC_TYPE_CANVAS_ERROR (asc_canvas_error_get_type())

/* enumerations from "asc-compose.h" */


GType asc_compose_flags_get_type (void);
#define ASC_TYPE_COMPOSE_FLAGS (asc_compose_flags_get_type())

/* enumerations from "asc-globals.h" */


GType asc_compose_error_get_type (void);
#define ASC_TYPE_COMPOSE_ERROR (asc_compose_error_get_type())

/* enumerations from "asc-icon-policy.h" */


GType asc_icon_state_get_type (void);
#define ASC_TYPE_ICON_STATE (asc_icon_state_get_type())

/* enumerations from "asc-image.h" */


GType asc_image_save_flags_get_type (void);
#define ASC_TYPE_IMAGE_SAVE_FLAGS (asc_image_save_flags_get_type())


GType asc_image_load_flags_get_type (void);
#define ASC_TYPE_IMAGE_LOAD_FLAGS (asc_image_load_flags_get_type())


GType asc_image_format_get_type (void);
#define ASC_TYPE_IMAGE_FORMAT (asc_image_format_get_type())


GType asc_image_error_get_type (void);
#define ASC_TYPE_IMAGE_ERROR (asc_image_error_get_type())

G_END_DECLS

/* Generated data ends here */

